#!/usr/bin/env bash
# Install Baresip from source (so call recording works), wipe any previous
# install/config, and write Callcentric settings from .env.
#
#   ./setup_baresip.sh          # install + configure
#   ./setup_baresip.sh --start  # then launch (IPv4, verbose)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$ROOT/.env"
REC_DIR="$ROOT/baresip_recordings"
BARESIP_DIR="${HOME}/.baresip"
START=0

if [[ "${1:-}" == "--start" ]]; then
  START=1
elif [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  echo "Usage: $0 [--start]"
  exit 0
fi

log() { printf '\n==> %s\n' "$*"; }

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "This script is for macOS (Homebrew + CoreAudio)." >&2
  exit 1
fi

if ! command -v brew >/dev/null 2>&1; then
  echo "Homebrew is required. Install it from https://brew.sh then re-run." >&2
  exit 1
fi

# Homebrew on Apple Silicon vs Intel
BREW_PREFIX="$(brew --prefix)"
export PATH="$BREW_PREFIX/bin:$PATH"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing $ENV_FILE (need SERVER, NUMBER, PASSWORD)." >&2
  exit 1
fi

env_get() {
  python3 - "$1" "$ENV_FILE" <<'PY'
import re, sys
key, path = sys.argv[1], sys.argv[2]
text = open(path, encoding="utf-8").read()
m = re.search(rf"^{re.escape(key)}\s*=\s*(.+)$", text, re.M)
if not m:
    sys.exit(1)
val = m.group(1).strip()
if len(val) >= 2 and val[0] == val[-1] and val[0] in "\"'":
    val = val[1:-1]
print(val, end="")
PY
}

SERVER="$(env_get SERVER)"
NUMBER="$(env_get NUMBER)"
PASSWORD="$(env_get PASSWORD)"

if [[ -z "$SERVER" || -z "$NUMBER" || -z "$PASSWORD" ]]; then
  echo ".env must set SERVER, NUMBER, and PASSWORD." >&2
  exit 1
fi

log "Stopping any running baresip"
pkill -x baresip 2>/dev/null || true
sleep 0.3

log "Removing previous Baresip install (Homebrew bottle often has no recorder)"
if brew list --formula baresip >/dev/null 2>&1; then
  brew uninstall --force baresip
fi

if [[ -e "$BARESIP_DIR" ]]; then
  BAK="${BARESIP_DIR}.bak.$(date +%Y%m%d-%H%M%S)"
  log "Backing up $BARESIP_DIR -> $BAK"
  mv "$BARESIP_DIR" "$BAK"
fi

log "Installing libsndfile (needed to compile the recording module)"
brew install libsndfile

export PKG_CONFIG_PATH="$(brew --prefix libsndfile)/lib/pkgconfig:${PKG_CONFIG_PATH:-}"

log "Building Baresip from source so sndfile.so is included"
brew install --build-from-source baresip

BARESIP_PREFIX="$(brew --prefix baresip)"
MOD_DIR="$BARESIP_PREFIX/lib/baresip/modules"
SNDFILE="$MOD_DIR/sndfile.so"
CTRL_TCP="$MOD_DIR/ctrl_tcp.so"

if [[ ! -f "$SNDFILE" ]]; then
  echo "sndfile.so was not built. Recording will not work." >&2
  echo "Make sure libsndfile is installed, then re-run this script." >&2
  exit 1
fi
if [[ ! -f "$CTRL_TCP" ]]; then
  echo "ctrl_tcp.so is missing; server.py will not be able to control Baresip." >&2
  exit 1
fi

mkdir -p "$REC_DIR" "$BARESIP_DIR"

log "Writing $BARESIP_DIR/config"
cat > "$BARESIP_DIR/config" <<EOF
#
# baresip configuration (generated by setup_baresip.sh)
#

# SIP
sip_cafile		/etc/ssl/cert.pem
sip_tos			160

# Call
call_local_timeout	120
call_max_calls		4
call_hold_other_calls	yes
call_accept		no

# Audio
audio_player		coreaudio,default
audio_source		coreaudio,default
audio_alert		coreaudio,default
audio_level		no
ausrc_format		s16
auplay_format		s16
auenc_format		s16
audec_format		s16
audio_buffer		20-160
audio_telev_pt		101

# Video
video_size		640x480
video_bitrate		1000000
video_fps		30.00
video_fullscreen	no
videnc_format		yuv420p

# AVT
rtp_tos			184
rtp_video_tos		136
audio_jitter_buffer_type	fixed
audio_jitter_buffer_ms	100-200
audio_jitter_buffer_size	50
video_jitter_buffer_type	fixed
video_jitter_buffer_ms	100-200
video_jitter_buffer_size	250
rtp_stats		no

#------------------------------------------------------------------------------
# Modules

module_path		$MOD_DIR

# UI: cons.so works without a TTY (stdio.so does not)
module			cons.so

# Codecs
module			g711.so

# Filters: sndfile first so incoming audio is converted then written
module			sndfile.so
module			auconv.so
module			auresamp.so

# Audio driver
module			coreaudio.so

# Compatibility / NAT
module			uuid.so
module			stun.so
module			turn.so
module			ice.so

#------------------------------------------------------------------------------
# Application Modules

module_app		account.so
module_app		contact.so
module_app		debug_cmd.so
module_app		menu.so
module_app		ctrl_tcp.so
module_app		netroam.so

#------------------------------------------------------------------------------
# Module parameters

cons_listen		0.0.0.0:5555
http_listen		0.0.0.0:8000
ctrl_tcp_listen		0.0.0.0:4444

snd_path		$REC_DIR
EOF
chmod 600 "$BARESIP_DIR/config"

log "Writing $BARESIP_DIR/accounts"
python3 - "$BARESIP_DIR/accounts" "$NUMBER" "$SERVER" "$PASSWORD" <<'PY'
import sys
path, number, server, password = sys.argv[1:5]
# Keep the line valid if the password contains ';' or '"'
password = password.replace("\\", "\\\\").replace(";", "\\;").replace('"', '\\"')
body = f'''#
# SIP accounts — generated by setup_baresip.sh
# SIP user is the Callcentric 1777 number (NUMBER in .env), not the email.
#
"Callcentric" <sip:{number}@{server}>;auth_user={number};auth_pass={password};outbound="sip:{server};transport=tcp";sipnat=outbound;regint=1800;mwi=no;answermode=manual;medianat=stun;stunserver=stun:stun.l.google.com:19302
'''
open(path, "w", encoding="utf-8").write(body)
PY
chmod 600 "$BARESIP_DIR/accounts"

log "Setup complete"
echo "  Baresip:     $(command -v baresip) ($(baresip -h 2>&1 | head -1 || true))"
echo "  Recording:   $REC_DIR"
echo "  Account:     sip:${NUMBER}@${SERVER}"
echo "  Control:     127.0.0.1:4444  (server.py)"
echo
echo "Allow Microphone access if macOS asks."
echo "Start with:  baresip -4"
echo "Or rerun:    $0 --start"

if [[ "$START" -eq 1 ]]; then
  log "Starting baresip (Ctrl-C to quit)"
  exec baresip -4 -v -T
fi
